name: "Ansible Workflow"

on:
  workflow_run:
    workflows: ["Terraform apply on merge"]
    types:
      - completed

jobs:
  ansible:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}     ## runs only if the the terraform apply on merge run successfully
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Setup AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: get the public ip address of the ec2 machine
      run: |
        PUBLIC_IP=$(terraform output -raw public_ip)
        echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
      working-directory: ./terraform

    - name: Get SSH key
      run: |
        aws secretsmanager get-secret-value \
        --secret-id ssh-keys/pipeline-ec2-5 \
        --query SecretString --output text | \
        jq -r '.private_key' > key.pem
        chmod 400 key.pem

    - name: install ansible
      run: |
        sudo apt update
        sudo apt install -y ansible


    - name: create inventory
      run: |
        echo "[web]" >> inventory
        echo "$PUBLIC_IP ansible_user=ubuntu ansible_ssh_private_key_file=key.pem" >> inventory

    - name: Add EC2 to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H $PUBLIC_IP >> ~/.ssh/known_hosts

    - name: build kind kubernetes infrastructure
      run: ansible-playbook -i inventory  ansible/kubernetes_infra.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: false






    
  

    

