name: "Ansible Workflow"

on:
  workflow_run:
    workflows: ["Terraform apply on merge"]
    types:
      - completed

jobs:
  ansible:
    name : 'ansible'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Setup AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: get the public ip address of the ec2 machine
      run: |
        PUBLIC_IP=$(terraform output -raw public_ip)
        echo "Public IP: $PUBLIC_IP" >> $GITHUB_ENV
      working-directory: ./terraform

    - name: Get SSH key
      run: |
        aws secretsmanager get-secret-value \
        --secret-id ssh-keys/pipeline-ec2-3 \
        --query SecretString --output text | \
        jq -r '.private_key' > key.pem
        chmod 400 key.pem
      
    - name: ssh into the machine
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ env.PUBLIC_IP }}
        username: ubuntu
        key: key.pem
        script: |
          echo "connected successfully Sudheesh"
          uname -a





    
  

    

